ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        additional_dependencies: ['toml']
        # not support auto read config from `pyproject.toml` for now
        args: ['-c', "pyproject.toml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: dev_datadir/
      - id: trailing-whitespace
      - id: name-tests-test
        args: [--django]
      - id: check-added-large-files
        args: [ --enforce-all ]
      - id: check-merge-conflict

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
